ref_gfa_path : "./reference_sequences/lDE26.gfa"
scratch_path : "/home/de64/scratch/de64/2023-03-10_lDE26_Nanopore_TestRun/"
fast5_path : "/home/de64/scratch/de64/2023-03-10_lDE26_Nanopore_TestRun/fast5_files"
flowcell : "FLO-MIN114"
kit : "SQK-LSK114"
min_readlength : 750
max_readlength : 1500
fast5_chunksize : 500
read_setsize : 200000
chunk_size : 50
depth_threshold : 180
n_subsamples : [0]