jobs: 1000
latency-wait: 60
rerun-incomplete: True
cluster: "sbatch -p {resources.partition} -n {resources.ntasks} -t {resources.time} --mem={resources.mem} -c {resources.cpus} -o logs/cluster/{rule}_{wildcards} -e logs/cluster/{rule}_{wildcards} {resources.optflags}"